test: add tests with null char at the end
Currently it fails because the null character is duplicated:

=== Running test test_null_end.test
ERROR: "test_null_end " exited with non-zero exit status: 1
ERROR: "test_null_end " (test_null_end) failed (set VERBOSE=1 to see full output):
+ diff /OE/projects/json-c-0.12/tests/test_null_end.expected testSubDir/test_null_end.test/test_null_end.out
1,3c1,5
< JSON write result is correct: " \u0000"
< PASS
< Re-parsed object string len=3, chars=[32, 0, 32]
---
> JSON write result doesn't match expected string
> expected string: " \u0000"
> parsed string:   " \u0000\u0000"
> FAIL
> Re-parsed object string len=2, chars=[32, 0]
cp "testSubDir/test_null_end.test/test_null_end.out" "/OE/projects/json-c-0.12/tests/test_null_end.expected"

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>