test: add tests with null char at the end
Currently it passes both test_null tests, but notice that it
depends on reverted fix for issue #53.

FAIL: test_null
===============

=== Running test test_null.test
ERROR: "test_null " (test_null) failed (set VERBOSE=1 to see full output):
+ diff /OE/projects/json-c/tests/test_null.expected testSubDir/test_null.test/test_null.out
3d2
< Re-parsed object string len=3, chars=[32, 0, 32]
cp "testSubDir/test_null.test/test_null.out" "/OE/projects/json-c/tests/test_null.expected"
FAIL test_null.test (exit status: 1)

FAIL: test_null_end
===================

=== Running test test_null_end.test
ERROR: "test_null_end " (test_null_end) failed (set VERBOSE=1 to see full output):
+ diff /OE/projects/json-c/tests/test_null_end.expected testSubDir/test_null_end.test/test_null_end.out
3d2
< Re-parsed object string len=3, chars=[32, 0, 32]
cp "testSubDir/test_null_end.test/test_null_end.out" "/OE/projects/json-c/tests/test_null_end.expected"
FAIL test_null_end.test (exit status: 1)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>